# Generated by Django 4.2 on 2023-06-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_hashtag_post_like_alter_post_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
